### ISSUE TITLE
Missing changelog

### ISSUE THREAD

**Issue by Xiretza** [KizzyCode/ezexec-rust#1]
Without a changelog, it's really hard to figure out what has changed between versions, and importantly what the breaking changes between major versions were. The commit log isn't helpful either, 8d282f9f2d78960635592bd959af57138defba70 is the only commit between 0.3.0 and 0.4.0 - the commit message explains nothing and there seem to be formatting changes intermixed with potential actualy changes.

**Comment by KizzyCode** [comment]
Fair point. Tbh I usually don't do changelogs for `0.`-releases, but it seems like I fucked up the commits and squashed functional commits together with `rustfmt` 😕 

I'm afraid I don't have the intermediate history anymore, sorry. If there any questions, please feel free to ask 😊

**Comment by KizzyCode** [comment]
Closing this now, please feel free to reopen if you want to discuss this further 😊
